# Generated by Django 4.2.7 on 2023-11-24 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_alter_vote_admins_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VoterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.vote_admins')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_name', models.CharField(max_length=100)),
                ('Num_Candidates', models.IntegerField(default=0)),
                ('Total_votes', models.IntegerField(default=0)),
                ('voting_admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.vote_admins')),
            ],
        ),
        migrations.CreateModel(
            name='Partylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party_name', models.CharField(max_length=150)),
                ('Logo', models.ImageField(upload_to='')),
                ('Description', models.TextField(blank=True)),
                ('voting_admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.vote_admins')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('voting_admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.vote_admins')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('header_order', models.JSONField()),
                ('voting_admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.vote_admins')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('candidates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotingAdmin.candidate')),
                ('partylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotingAdmin.partylist')),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VotingAdmin.positions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting_admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.vote_admins')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='VotingAdmin.candidateapplication'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='voting_admins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.vote_admins'),
        ),
    ]
