# Generated by Django 4.2.7 on 2023-11-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_alter_vote_admins_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_name', models.CharField(max_length=100)),
                ('Num_Candidates', models.IntegerField(default=0)),
                ('Total_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('header_order', models.JSONField()),
                ('voting_admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.vote_admins')),
            ],
        ),
    ]
