# Generated by Django 4.2.7 on 2023-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos_name', models.CharField(max_length=100)),
                ('Num_Candidates', models.IntegerField(default=0)),
                ('Total_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
