# Generated by Django 4.2.7 on 2023-11-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='VotingAdmin.election'),
        ),
    ]
