# Generated by Django 4.2.7 on 2023-11-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvupload',
            name='voting_admins',
        ),
        migrations.DeleteModel(
            name='Positions',
        ),
        migrations.DeleteModel(
            name='CSVUpload',
        ),
    ]
