# Generated by Django 4.2.7 on 2023-11-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0002_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDynamicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('\ufeffFirst_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Office', models.CharField(max_length=255)),
            ],
        ),
    ]
