# Generated by Django 4.2.7 on 2023-11-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0002_remove_candidate_status_candidateapplication_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateapplication',
            name='candidates',
        ),
    ]
