# Generated by Django 4.2.6 on 2023-11-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0002_dynamiccsvmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicCSVModel',
        ),
    ]
