# Generated by Django 4.2.7 on 2023-11-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0003_votelog_voterelection'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='VotingAdmin.election'),
            preserve_default=False,
        ),
    ]
