# Generated by Django 4.2.7 on 2024-01-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0003_delete_choice_delete_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
