# Generated by Django 4.2.7 on 2024-01-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0004_election_end_date_election_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='start_date',
        ),
    ]
