# Generated by Django 4.2.7 on 2023-11-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_vote_admins_user'),
        ('VotingAdmin', '0004_voterprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party_name', models.CharField(max_length=150)),
                ('Logo', models.ImageField(upload_to='')),
                ('Description', models.TextField(blank=True)),
                ('voting_admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.vote_admins')),
            ],
        ),
    ]
