# Generated by Django 4.2.7 on 2023-11-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0005_candidateapplication_election'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='partylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_list', to='VotingAdmin.partylist'),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='positions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='VotingAdmin.positions'),
        ),
    ]
