# Generated by Django 4.2.7 on 2023-11-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0006_remove_election_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='election',
            name='start_time',
        ),
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
