# Generated by Django 4.2.7 on 2023-11-27 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0007_remove_election_end_time_remove_election_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='election',
        ),
    ]
