# Generated by Django 4.2.7 on 2023-11-27 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0008_remove_positions_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VotingAdmin.election'),
        ),
    ]
