# Generated by Django 4.2.7 on 2023-11-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0010_positions_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='votelog',
            name='position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='VotingAdmin.positions'),
            preserve_default=False,
        ),
    ]
