# Generated by Django 4.2.7 on 2023-11-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingAdmin', '0011_votelog_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votelog',
            old_name='user',
            new_name='voter',
        ),
    ]
