# Generated by Django 4.2.6 on 2023-10-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('organization', models.CharField(blank=True, default=None, max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientadmin',
            name='Sysadmin',
        ),
        migrations.DeleteModel(
            name='UseRequest',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='ClientAdmin',
        ),
        migrations.DeleteModel(
            name='SystemAdmin',
        ),
    ]
