# Generated by Django 4.2.6 on 2023-10-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_requestform_remove_clientadmin_sysadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emaill', models.CharField(max_length=100)),
                ('orgz', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Requestform',
        ),
    ]
