# Generated by Django 4.2.6 on 2023-10-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_votingadmins_delete_requestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingadmins',
            name='org_code',
            field=models.CharField(default=None, max_length=8, unique=True),
        ),
    ]
