# Generated by Django 4.2.6 on 2023-10-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_votingadmins_org_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingadmins',
            name='org_code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
