# Generated by Django 4.2.6 on 2023-10-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_alter_votingadmins_org_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VotingAdmins',
        ),
    ]
