# Generated by Django 4.2.6 on 2023-10-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0010_delete_votingadmins'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emaill', models.CharField(max_length=100)),
                ('orgz', models.CharField(max_length=100)),
                ('org_code', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
