# Generated by Django 4.2.6 on 2023-10-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_alter_votingadmins_org_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingadmins',
            name='org_code',
            field=models.CharField(blank=True, default='None', max_length=8),
        ),
    ]
