# Generated by Django 4.2.6 on 2023-10-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingadmins',
            name='org_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
