# Generated by Django 4.2.6 on 2023-10-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0017_votingadmin_delete_votingadmins'),
    ]

    operations = [
        migrations.CreateModel(
            name='vote_admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emaill', models.CharField(max_length=100)),
                ('orgz', models.CharField(max_length=100)),
                ('org_code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Votingadmin',
        ),
    ]
