# Generated by Django 4.2.6 on 2023-10-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingsystembase', '0002_requestform_organization_requestform_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='status',
        ),
    ]
