# Generated by Django 4.2.6 on 2023-10-24 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votingsystembase', '0003_remove_requestform_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='organization',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
