# Generated by Django 4.2.6 on 2023-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingsystembase', '0005_remove_requestform_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='organization',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
